server:
  port: 8079
spring:
  application:
    name: VinaAcademy-Platform
  profiles:
    active: dev, mail

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#server:
#  address: 0.0.0.0
#  port: 8080